# Generated by Django 4.1 on 2023-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saves",
            field=models.ManyToManyField(to="products.products"),
        ),
    ]
