# Generated by Django 4.1 on 2023-01-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_saves"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userStringLocation",
            field=models.CharField(default="No Location", max_length=255),
            preserve_default=False,
        ),
    ]
