# Generated by Django 4.1 on 2022-08-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_user_mobilenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saves',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
