# Generated by Django 4.1 on 2023-01-18 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_userstringlocation"),
    ]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[],),
        migrations.AlterField(
            model_name="user",
            name="userLocation",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
